name: Upload Crowdin files

# on any push to main, we upload the translations to be translated
on:
  push:
    branches:
      - main

jobs:
  upload-to-crowdin:
    name: Upload sources to Crowdin
    runs-on:
        group: larger

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Synchronize
        uses: crowdin/github-action@97aa99cbebfe99b964e3521e6421c1518146d4b9 # v1.4.12
        with:
          upload_sources: true
          download_translations: false
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
